### ISSUE TITLE
Med.& Farm. Tovarovedenie

### ISSUE THREAD

**Issue by DashaGryaznova** [DashaGryaznova/8-semestr-NIR1#1]
[Семейство глюкометров CONTOUR.pdf](https://github.com/DashaGryaznova/8-semestr-NIR1/files/4849754/CONTOUR.pdf)
[Тесты по дисциплине МТВ.docx](https://github.com/DashaGryaznova/8-semestr-NIR1/files/4849756/default.docx)

**Comment by Nadushich97** [comment]
Я вижу работу
